services:
  ai-tarot-divination:
    image: ghcr.io/dreamhunter2333/ai-tarot-divination:latest
    container_name: ai-tarot-divination
    restart: always
    ports:
      - 8000:8000
    environment:
      - api_key=sk-xxx
      # - api_base=https://openrouter.ai/api/v1 # optional
      # - model=anthropic/claude-sonnet-4 # optional
      # - rate_limit=10/minute # optional
      # - user_rate_limit=600/hour # optional
      - github_client_id=xxx
      - github_client_secret=xxx
      - jwt_secret=secret
      - ad_client=ca-pub-xxx
      - ad_slot=123
